##===- tools/COTPasses/Makefile ----------------------------*- Makefile -*-===##

LEVEL = ../..

LIBRARYNAME = COTPasses

LOADABLE_MODULE = 1

USEDLIBS = cotHelloLLVM.a

include $(LEVEL)/Makefile.common
